Refactoring
KWaniova/PharmacophoresProject pull request #1
Opened 2024-05-22 20:23 UTC by KWaniova

2024-05-28 08:15 UTC, mokosaur requested changes
Przejrzałem kod na szybko, wygląda to fajnie. Można spróbować puścić jeszcze `black` i `isort` (w terminalu wystarczy wpisać np. `back [ścieżka do folderu z projektem]`, to ładnie sformatuje kod.

2024-05-28 13:40 UTC, KWaniova commented on src/datasets/dataset_loader.py
> +if '../utils' not in sys.path:
Próbując używać tej formy `from src.utils import ...` wyrzuca mi błąd przy imporcie pliku:
<img width="725" alt="Screenshot 2024-05-28 at 15 37 44" src="https://github.com/KWaniova/PharmacophoresProject/assets/61587204/4a0e85e8-eb92-476e-9408-2fc3ab5c03db">

2024-06-05 23:36 UTC, mokosaur reviewed
Dodałem jeszcze parę komentarzy. Usunąłem pliki .DS_Store, bo dalej były w tym branchu mimo dodania do .gitignore (były dodane przed zignorowaniem, więc zostały na branchu).

Poza tym można zastanowić się nad przeniesieniem notebooków do osobnego folderu `notebooks` w głównym folderze (obok `src`). Teraz te wszystkie kopie trochę zaśmiecają folder `main` ;)

Poza tym też do zastanowienia się, czy chcesz trzymać wytrenowane modele na repo. Może trzymać je tylko lokalnie, skoro każdy może te modele wytrenować kodem od zera. Przez pliki z wagami repo zrobiło się dość ciężkie.

Ogólnie kod wygląda bardzo fajnie. Nie mam większych uwag.

2024-06-05 23:36 UTC, mokosaur commented on datasets_configs.yml
> +dataset_1:
Nie wiem, czy tutaj te nazwy `dataset_x` coś wnoszą. Wydaje mi się, że można byłoby w yml zrobić listę słowników tak:
```
- columns:
  - Drug
  - Y
  name: hERG
  path: datasets/herg
  task: classification
- columns:
  - mol
  - Class
  ...
```

2024-06-05 23:36 UTC, mokosaur commented on README.md
Przydałaby się instrukcja, który plik albo który notebook służy do trenowania modeli. Żeby użytkownik od razu wiedział, gdzie zacząć.

2024-06-05 23:36 UTC, mokosaur commented on src/datasets/bbb/data/bbb_martins.tab
Te pliki też chyba można usunąć z repo. To jest plik ściągany automatycznie kodem TDC?

2024-06-06 08:34 UTC, KWaniova commented on src/datasets/bbb/data/bbb_martins.tab
Tak to plik automatycznie ściągany, dodam je do gitignore w takim razie

2024-06-06 09:00 UTC, KWaniova commented on datasets_configs.yml
> +dataset_1:
To jest tak jakby ich id, łatwiej jest przez to wybrać zbiór na którym model ma być trenowany, najwyżej można by to zastąpić dodaniem pola id dla każdego zbioru w yml?

2024-06-06 11:50 UTC, mokosaur commented on datasets_configs.yml
> +dataset_1:
Jeśli jest to używane jako id, to niech zostanie. Myślałem, że to jest zbędna informacja, ale w yamlu tak było wygodniej zrobić.

2024-06-06 11:51 UTC, mokosaur commented on src/datasets/bbb/data/bbb_martins.tab
👍

2024-06-11 11:06 UTC, KWaniova reviewed
Zrefaktoryzawałam jeszcze grid search dla modeli, usunęłam niepotrzebne pliki, dodałam do .gitignore dane ściągane i przetwarzane, przesunęłam notebooki do folderu notebooks w głównym folderze projektu i dodałam opis do README. Dodałam też plik skryptowy do treningu modeli. W notebooku split-analysis dodałam skrypt do wizualizacji t-sne datasetów oraz notebook do wizualizacji przebiegu uczenia modeli i wyników.

2024-06-11 14:28 UTC, merged